apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-users
data:
  port: "8001"
  db_host: "msvc-users-db:3306"
  database: msvc_users
#  username: root
#  password: sasa
  courses_url: msvc-courses:8002
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: msvc-courses
  data:
    port: "8002"
    db_host: "msvc-courses-db:3306"
    database: msvc_courses
#    username: root
#    password: sasa
    users_url: msvc-users:8001